[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = ['less']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = ['jade']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['leafgarland/typescript-vim']
on_ft = ['typescript, typescript.tsx']


[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'github/copilot.vim'
on_ft = ['copilot']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'ruby.erb', 'ruby.slim']

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'junegunn/gv.vim'
